const ActionNames = {
  UPDATE_MESSAGES: "UPDATE_MESSAGES",
  LOAD_MESSAGES: "LOAD_MESSAGES",
  SET_SESSION: "SET_SESSION",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL"
};

export default ActionNames;
