const ActionNames = {
  UPDATE_MESSAGES: "UPDATE_MESSAGES",
  LOAD_MESSAGES: "LOAD_MESSAGES",
  SET_SESSION: "SET_SESSION",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_SESSION_NAME_INPUT_ERROR: "SET_SESSION_NAME_INPUT_ERROR",
  CLEAR_SESSION_NAME_INPUT_ERROR: "CLEAR_SESSION_NAME_INPUT_ERROR"
};

export default ActionNames;
